### ISSUE TITLE
cursorBlink overwritten by theme

### ISSUE THREAD

**Issue by OfficerHalf** [arcticicestudio/nord-hyper#15]
Instead of checking config.cursorBlink, the theme checks nordHyper.cursorBlink, which is always set to true. I can modify the nord-hyper index.js, but it will be overwritten on update.

This should not overwrite the main hyper settings.

EDIT: Ah, I see now. #12 . I guess I'll just wait until the next release, or create a local version of the plugin.

**Comment by arcticicestudio** [comment]
> Duplicate of #10

Sorry for the release delay, had no time to package a new version. I currently work on some long pending things during my winter vacation. Made a new TODO task for today to get this fix out asap :smile:

**Comment by arcticicestudio** [comment]
Released version [0.5.0][v] which includes the fix.

[v]: https://github.com/arcticicestudio/nord-hyper/releases/tag/v0.5.0
