### ISSUE TITLE
Use custom fontFamily?

### ISSUE THREAD

**Issue by kepbod** [arcticicestudio/nord-hyper#2]
According to [index.js](https://github.com/arcticicestudio/nord-hyper/blob/b1fde2946b261ff5c4306605ed883285da4984e9/index.js#L65), nord-hyper uses `Source Code Pro` or `Hack` font first. If users set the custom fontFamily, it won't use it. Are there any solutions? Thanks a lot.

PS: I found a typo in the [README](https://github.com/arcticicestudio/nord-hyper/blame/b1fde2946b261ff5c4306605ed883285da4984e9/README.md#L23), and it should be `⌘ + ,` instead of `⌘ +`.

**Comment by arcticicestudio** [comment]
This is a bug, the order should be to use `config.fontFamily` first the defind fonts as alternative/fallback.
I'll fix the typo as the order with the next patch, thanks 👍

**Comment by arcticicestudio** [comment]
Fixed in #3 and shipped in npm :package: release version :label: [0.1.1](https://github.com/arcticicestudio/nord-hyper/releases/tag/v0.1.1)

**Comment by kepbod** [comment]
Cool 👍
