### ISSUE TITLE
Bug: Padding on the cursor

### ISSUE THREAD

**Issue by wcastand** [arcticicestudio/nord-hyper#4]
![lien](http://img11.hostingpics.net/pics/466508Capturedecran20170301a181623.png)

Hello, first of all, really nice theme 👍 

As you can see on the picture, my cursor's real position and his visual position are different.
I used the theme [hyper-dark-dracula](https://www.npmjs.com/package/hyper-dark-dracula) before and i didn't have this problem :/

If i can help, let me know ;)

My config : 

- OSX Sierra 10.12.3
- Hyper.app Version 1.2.1 (1.2.1.1527)
- i use oh-my-zsh with the theme [pure](https://github.com/sindresorhus/pure)

my hyper config : 
```
module.exports = {
  config: {
    fontSize: 11,
    fontFamily: 'Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
    cursorColor: 'rgba(248,28,229,0.8)',
    cursorShape: 'BEAM',

    foregroundColor: '#fff',
    backgroundColor: '#000',
    borderColor: '#333',
    css: '',
    termCSS: '',
    showHamburgerMenu: '',
    showWindowControls: 'false',
    padding: '12px 14px 0px 14px',
    colors: {
      black: '#000000',
      red: '#ff0000',
      green: '#33ff00',
      yellow: '#ffff00',
      blue: '#0066ff',
      magenta: '#cc00ff',
      cyan: '#00ffff',
      white: '#d0d0d0',
      lightBlack: '#808080',
      lightRed: '#ff0000',
      lightGreen: '#33ff00',
      lightYellow: '#ffff00',
      lightBlue: '#0066ff',
      lightMagenta: '#cc00ff',
      lightCyan: '#00ffff',
      lightWhite: '#ffffff'
    },
    shell: '',
    shellArgs: ['--login'],
    env: {},
    bell: 'false',
    copyOnSelect: true
  },
  plugins:["nord-hyper", "hypercwd", "hyperterm-1password", "hyper-statusline"],

  localPlugins: []
};
```

**Comment by arcticicestudio** [comment]
Nice to see you like it 😄 
I tried to reproduce it with exact the same setup. but for me the cursor is at the correct position.
This may also be caused by a `oh-my-zsh` plugin like plugins that are changing the prompt.

Can you please post your `~/.zshrc` config so I can try to reproduce it with the same ZSH plugins enabled?

**Comment by wcastand** [comment]
This is ma zshrc, the "I" is red because of the plugin 'zsh-syntax-highlighting'.

I tried to disable all my zsh plugin and pure prompt. But i still get the padding :/

```
# Path to your oh-my-zsh installation.
export ZSH=/Users/willoo/.oh-my-zsh
COMPLETION_WAITING_DOTS="true"
# ZSH_THEME="agnoster"
# ZSH_THEME="pure"
ZSH_THEME="honukai"

plugins=(git node npm github colorize brew osx zsh-syntax-highlighting)

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"
export EDITOR='code'

alias st='git status'
alias ci='git commit'
alias co='git checkout'
alias br='git branch'
alias fe='git fetch -p'
alias gaa='git add --all'
alias push='git push'
alias pushh='git push origin HEAD'
alias pull='git pull'
alias dbr='git branch --merged | egrep -v "(^\*|master|develop|release)" | xargs git branch -d'

alias ll='ls -la'

alias cl='clear'
alias run='npm run'

alias kilix='cd ~/Documents/Kilix/'
alias project='cd ~/Documents/Projects/'
alias vamos='cd ~/Documents/Kilix/vamos'
alias vamos-api='cd ~/Documents/Kilix/vamos-api'
alias vamos-docker='cd ~/Documents/Kilix/vamos-docker'

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
export LANG=fr_FR.UTF-8

DEFAULT_USER=`whoami`

export PATH="$HOME/.yarn/bin:$PATH"
export PATH="$HOME/.npm-packages/bin:$PATH"

autoload -U promptinit; promptinit
prompt pure
```

**Comment by arcticicestudio** [comment]
Unfortunately I'm still not able to reproduce it, with your exact setup or small changes.
At this point I don't know how to solve your problem, sorry 😞 

It would be nice if you could post here (I'll let this issue open) if you're able to find the cause of this strange behavior or a functional way to reproduce it.

**Comment by arcticicestudio** [comment]
I've read through the Hyper issues and maybe your issue is related to [zeit/hyper #1227](https://github.com/zeit/hyper/issues/1227) which may be fixed in [zeit/hyper PR #1376](https://github.com/zeit/hyper/pull/1376).

**Comment by zovt** [comment]
The problem is that the latest release on NPM is still 0.1.0 which overrides a lot of configs in your `.hyper.js` file, and you don't have the fonts specified by the theme installed. Until #5 is fixed, for right now you can do the following:

```
cd ~/.hyper_plugins/node_modules
rm -rf nord-hyper
git clone https://github.com/arcticicestudio/nord-hyper
```
which should grab the 0.1.1 release

**Comment by wcastand** [comment]
it works thanks ;)
I close this :)

**Comment by arcticicestudio** [comment]
Good to hear it solved your problem 😄 
I've posted a description about the problem in #5.
