### ISSUE TITLE
[Suggestion] Make cursor blink toggleable

### ISSUE THREAD

**Issue by zovt** [arcticicestudio/nord-hyper#7]
Currently, I have a [fork](https://github.com/zovt/nord-hyper-no-cursor-blink) that disables cursor blink. It would be preferable if the blink was a feature that could be toggled in a configuration option.

I can implement this, but I won't get around to it until the weekend.

**Comment by arcticicestudio** [comment]
👍 Yes, I totally agree. This should be toggeable to not override user preferences or force users to use this feature.
I'll go for it tomorrow evening.

**Comment by zovt** [comment]
👍 excellent! Thanks 😄

**Comment by arcticicestudio** [comment]
I've implemented a configuration attribute to set the cursor blinking feature.
It can be tested by checking out  🌱 [feature/ghi-#7-make-cursor-blink-toggleable](https://github.com/arcticicestudio/nord-hyper/tree/feature/ghi-%237-make-cursor-blink-toggleable).

Information on how to configure Nord Hyper can be found in the [configuration section in the README](https://github.com/arcticicestudio/nord-hyper/tree/feature/ghi-%237-make-cursor-blink-toggleable#configuration).

**Comment by zovt** [comment]
Excellent! When will this be released?

**Comment by arcticicestudio** [comment]
I'll prepare the next release version now to push it to NPM.

**Comment by arcticicestudio** [comment]
🚢 Shipped in release version 🏷  [0.3.0](https://github.com/arcticicestudio/nord-hyper/releases/tag/v0.3.0) and pushed as NPM :package: package update.

**Comment by zovt** [comment]
I think hyper just released a new version that includes some built in option for cursor blinking. Maybe it would make sense to check that option instead?
